USE [Cerberus]
GO

UPDATE [dbo].[SETTINGS_MAIN] SET [SETTING]='VERSION_ID' WHERE [SETTING]='UPDATER_KEY' GO
UPDATE [dbo].[SETTINGS_MAIN] SET [VALUE]='3.7.2' WHERE [SETTING]='VERSION' GO
UPDATE [dbo].[SETTINGS_MAIN] SET [VALUE]='1ANfVGFdF2j2CZQPyZL60E3p' WHERE [SETTING]='VERSION_ID' GO

/*
UPDATE [dbo].[SETTINGS_MAIN] SET [VALUE]='3.7.1' WHERE [SETTING]='VERSION' GO
UPDATE [dbo].[SETTINGS_MAIN] SET [VALUE]='NHMzbFqcAFaFzSNH9MQO3VqBa' WHERE [SETTING]='VERSION_ID' GO
*/