IF OBJECT_ID('[Cerberus].[dbo].[SETTINGS_SOCIAL]', 'U') IS NOT NULL
DROP TABLE [Cerberus].[dbo].[SETTINGS_SOCIAL]
GO

CREATE TABLE [Cerberus].[dbo].[SETTINGS_SOCIAL](
	[RowID]		[int]			IDENTITY(1,1)	NOT NULL,
	[SETTING]	[varchar](50)					NULL,
	[VALUE]		[varchar](max)					NULL
)ON [PRIMARY]
GO

-- Records of SETTINGS_SOCIAL
INSERT INTO [Cerberus].[dbo].[SETTINGS_SOCIAL]
	VALUES (N'SOCIAL_URL_FACEBOOK',		N'');
INSERT INTO [Cerberus].[dbo].[SETTINGS_SOCIAL]
	VALUES (N'SOCIAL_URL_GOOGLEPLUS',	N'');
INSERT INTO [Cerberus].[dbo].[SETTINGS_SOCIAL]
	VALUES (N'SOCIAL_URL_PINTEREST',	N'');
INSERT INTO [Cerberus].[dbo].[SETTINGS_SOCIAL]
	VALUES (N'SOCIAL_URL_TWITTER',		N'');
GO