<?php
	$cat	=	isset($_REQUEST['cat']) ? $this->Data->escData(trim($_REQUEST['cat'])) : false;

	# Content
	echo '<div class="blog-page">';
		echo '<div class="container">';
			echo '<div class="row">';
				echo '<div class="col-md-9 col-sm-8 col-xs-7">';
					echo '<div class="blog-main">';
						echo '<div class="articles">';
							$this->SQL->get_blog_articles($cat);
						echo '</div>'; # end articles
					echo '</div>';
				echo '</div>';

				echo '<div class="col-md-3 col-sm-4 col-xs-5">';
					echo '<aside class="blog-aside">';
						# Categories
						echo '<div class="blog-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h3 class="blog-title">Categories<span class="line line--title line--blog-title"><span class="line__first"></span><span class="line__second"></span></span></h3>';
							echo '<div class="categories">';
								echo '<div class="categories__one">';
									echo '<header class="categories__head clearfix">';
										echo '<h5 class="pull-left"><a class="no-decoration" href="?'.$this->Setting->PAGE_PREFIX.'=Blog&amp;cat=mr">Members\' Rides</a></h5>';
										echo '<div class="categories__count pull-right">['.$this->SQL->get_count_members_rides().']</div>';
									echo '</header>';
									echo '<p class="categories__desc">Post your riding experiences.</p>';
								echo '</div>';
								echo '<div class="categories__one">';
									echo '<header class="categories__head clearfix">';
										echo '<h5 class="pull-left"><a class="no-decoration" href="?'.$this->Setting->PAGE_PREFIX.'=Blog&amp;cat=mn">Monthly Newsletters</a></h5>';
										echo '<div class="categories__count pull-right">['.$this->SQL->get_count_monthly_newsletters().']</div>';
									echo '</header>';
								echo '</div>';
								echo '<div class="categories__one">';
									echo '<header class="categories__head clearfix">';
										echo '<h5 class="pull-left"><a class="no-decoration" href="?'.$this->Setting->PAGE_PREFIX.'=Blog&amp;cat=rdr">Recalls, Defects & Repairs</a></h5>';
										echo '<div class="categories__count pull-right">['.$this->SQL->get_count_recalls().']</div>';
									echo '</header>';
									echo '<p class="categories__desc">Information On Recalls, Defects & Repairs</p>';
								echo '</div>';
								echo '<div class="categories__one">';
									echo '<header class="categories__head clearfix">';
										echo '<h5 class="pull-left"><a class="no-decoration" href="?'.$this->Setting->PAGE_PREFIX.'=Blog&amp;cat=sm">Swap Meets</a></h5>';
										echo '<div class="categories__count pull-right">['.$this->SQL->get_count_swap_meets().']</div>';
									echo '</header>';
									echo '<p class="categories__desc">';
										echo 'Members\' Buy, Sell & Trading Area';
									echo '</p>';
								echo '</div>';
								echo '<div class="categories__one">';
									echo '<header class="categories__head clearfix">';
										echo '<h5 class="pull-left"><a class="no-decoration" href="?'.$this->Setting->PAGE_PREFIX.'=Blog&amp;cat=ule">Upcoming Local Events</a></h5>';
										echo '<div class="categories__count pull-right">['.$this->SQL->get_count_upcoming_local_events().']</div>';
									echo '</header>';
									echo '<p class="categories__desc">Poker Runs & Other Events</p>';
								echo '</div>';
								
							echo '</div>';
						echo '</div>';

/*
						echo '<div class="blog-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<div class="aside-tabs">';
								echo '<div class="aside-tabs__links">';
									echo '<a href="#" class="no-decoration aside-tabs__active-link js-tab-link" data-for="#block1">Popular</a>';
									echo '<a href="#" class="no-decoration js-tab-link" data-for="#block2">Recent</a>';
								echo '</div>';
								echo '<div class="aside-tabs__blocks js-tab-block" id="block1">';
									echo '<div class="aside-tabs__block">';
										echo '<div class="row row--no-padding">';
											echo '<div class="col-xs-4">';
												echo '<img src="'.$this->Style->get_STYLE_MEDIA_DIR().'72x72/popular1.jpg" alt="moto" class="img-responsive" />';
											echo '</div>';
											echo '<div class="col-xs-7">';
												echo '<div class="aside-tabs__anons">';
													echo '<p><a class="no-decoration" href="article.html">Nunc molestie sapien tempor placerat ...</a></p>';
													echo '<div class="aside-tabs__date">March 30, 2015</div>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
									echo '<div class="aside-tabs__block">';
										echo '<div class="row row--no-padding">';
											echo '<div class="col-xs-4">';
												echo '<img src="'.$this->Style->get_STYLE_MEDIA_DIR().'72x72/popular2.jpg" alt="moto" class="img-responsive" />';
											echo '</div>';
											echo '<div class="col-xs-7">';
												echo '<div class="aside-tabs__anons">';
													echo '<p> <a class="no-decoration" href="article.html">Cras et lectus. Etiam amet turpis diset ...</a></p>';
													echo '<div class="aside-tabs__date">March 30, 2015</div>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
									echo '<div class="aside-tabs__block">';
										echo '<div class="row row--no-padding">';
											echo '<div class="col-xs-4">';
												echo '<img src="'.$this->Style->get_STYLE_MEDIA_DIR().'72x72/popular3.jpg" alt="moto" class="img-responsive" />';
											echo '</div>';
											echo '<div class="col-xs-7">';
												echo '<div class="aside-tabs__anons">';
													echo '<p><a class="no-decoration" href="article.html">Nunc molestie sapien tempor placerat ...</a></p>';
													echo '<div class="aside-tabs__date">March 30, 2015</div>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
									echo '<div class="aside-tabs__block">';
										echo '<div class="row row--no-padding">';
											echo '<div class="col-xs-4">';
												echo '<img src="'.$this->Style->get_STYLE_MEDIA_DIR().'72x72/popular4.jpg" alt="moto" class="img-responsive" />';
											echo '</div>';
											echo '<div class="col-xs-7">';
												echo '<div class="aside-tabs__anons">';
													echo '<p><a class="no-decoration" href="article.html">Amet turpis disce erat Ut proin a ipsum</a></p>';
													echo '<div class="aside-tabs__date">March 30, 2015</div>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="aside-tabs__blocks js-tab-block" id="block2">';
									echo '<div class="aside-tabs__block">';
										echo '<div class="row row--no-padding">';
											echo '<div class="col-xs-4">';
												echo '<img src="'.$this->Style->get_STYLE_MEDIA_DIR().'72x72/popular2.jpg" alt="moto" class="img-responsive" />';
											echo '</div>';
											echo '<div class="col-xs-7">';
												echo '<div class="aside-tabs__anons">';
													echo '<p><a class="no-decoration" href="article.html"> Cras et lectus. Etiam amet turpis diset ...</a></p>';
													echo '<div class="aside-tabs__date">March 30, 2015</div>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
									echo '<div class="aside-tabs__block">';
										echo '<div class="row row--no-padding">';
											echo '<div class="col-xs-4">';
												echo '<img src="'.$this->Style->get_STYLE_MEDIA_DIR().'72x72/popular3.jpg" alt="moto" class="img-responsive" />';
											echo '</div>';
											echo '<div class="col-xs-7">';
												echo '<div class="aside-tabs__anons">';
													echo '<p><a class="no-decoration" href="article.html">Nunc molestie sapien tempor placerat ...</a></p>';
													echo '<div class="aside-tabs__date">March 30, 2015</div>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
									echo '<div class="aside-tabs__block">';
										echo '<div class="row row--no-padding">';
											echo '<div class="col-xs-4">';
												echo '<img src="'.$this->Style->get_STYLE_MEDIA_DIR().'72x72/popular4.jpg" alt="moto" class="img-responsive" />';
											echo '</div>';
											echo '<div class="col-xs-7">';
												echo '<div class="aside-tabs__anons">';
													echo '<p><a class="no-decoration" href="article.html">Amet turpis disce erat Ut proin a ipsum</a></p>';
													echo '<div class="aside-tabs__date">March 30, 2015</div>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
					
						# Photos
						echo '<div class="blog-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h3 class="blog-title">Photos<span class="line line--title line--blog-title"><span class="line__first"></span><span class="line__second"></span></span></h3>';
							echo '<div class="blog-aside__photos">';
								echo '<div class="row row--small-padding">';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/photo1.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/photo2.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/photo3.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/footer1.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/footer2.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/footer3.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/photo4.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/photo5.jpg" /></a>';
									echo '</div>';
									echo '<div class="col-xs-4">';
										echo '<a class="fancyimage" data-fancybox-group="group" href="'.$this->Style->get_STYLE_MEDIA_DIR().'530x360/bike1.jpg"><img alt="bike" class="img-responsive" src="'.$this->Style->get_STYLE_MEDIA_DIR().'80x80/photo6.jpg" /></a>';
									echo '</div>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
						echo '<div class="blog-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h3 class="blog-title">Tags<span class="line line--title line--blog-title"><span class="line__first"></span><span class="line__second"></span></span></h3>';
							echo '<div class="blog-aside__tags">';
								echo '<a href="#" class="btn button button--grey button--tag triangle">Latest Bikes</a>';
								echo '<a href="#" class="btn button button--grey button--tag triangle">Motorcycles</a>';
								echo '<a href="#" class="btn button button--grey button--tag triangle">SEO</a>';
								echo '<a href="#" class="btn button button--grey button--tag triangle">Races</a>';
								echo '<a href="#" class="btn button button--grey button--tag triangle">Club Membership</a>';
								echo '<a href="#" class="btn button button--grey button--tag triangle">Event</a>';
								echo '<a href="#" class="btn button button--grey button--tag triangle">Upcoming Events</a>';
								echo '<a href="#" class="btn button button--grey button--tag triangle">2015 Bikes</a>';
							echo '</div>';
						echo '</div>';
						*/
						# Advertisements Block
						echo '<div class="blog-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h3 class="blog-title">Advertise Here<span class="line line--title line--blog-title"><span class="line__first"></span><span class="line__second"></span></span></h3>';
							echo '<ul class="js-latest-slider enable-bx-slider" data-auto="true" data-auto-hover="true" data-mode="horizontal" data-pager="false" data-pager-custom="null" data-prev-selector="null" data-next-selector="null">';
								echo '<li>';
									echo '<div class="latest-model">';
										echo '<div class="latest-model__img">';
											echo '<img alt="bike" class="img-responsive" src="'.$this->Style->MEDIA_DIR().'270x270/A&I_logo2_270x270.png" />';
										echo '</div>';
										echo '<div class="latest-model__info">';
											echo '<h5>Asphalt & Iron – A Life Behind Bars</h5>';
											echo '<p class="blog-text">';
												echo '<b>The Ultimate Social Network for Bikers, By Bikers</b><br>';
												echo '<b><a class="no-decoration" href="http://www.asphaltandiron.com">Asphalt & Iron Home</a></b><br>';
												echo '<b><a class="no-decoration" href="http://www.facebook.com/asphaltandiron">Visit Us On Facebook</a></b><br>';
												echo '<b><a href="mailto:info@asphaltandiron.com" target="_top">Send Us An Message</a></b>';
											echo '</p>';
										echo '</div>';
									echo '</div>';
								echo '</li>';
								echo '<li>';
									echo '<div class="latest-model">';
										echo '<div class="latest-model__img">';
											echo '<img alt="bike" class="img-responsive" src="'.$this->Style->MEDIA_DIR().'270x270/mickeys_1.png" />';
										echo '</div>';
									echo '</div>';
								echo '</li>';
								echo '<li>';
									echo '<div class="latest-model">';
										echo '<div class="latest-model__img">';
											echo '<img alt="bike" class="img-responsive" src="'.$this->Style->MEDIA_DIR().'270x270/mickeys_2.png" />';
										echo '</div>';
									echo '</div>';
								echo '</li>';
								echo '<li>';
									echo '<div class="latest-model">';
										echo '<div class="latest-model__info">';
											echo '<h5>Howells Cycle</h5>';
											echo '<p class="blog-text">';
												echo '<b>Address</b><br>';
												echo '8142 FM 16<br>';
												echo 'Van, TX 75790<br><br>';
												echo '<b>Phone</b><br>';
												echo '(903) 963-8953<br><br>';
												echo '<b>Business Hours</b><br>';
												echo 'Open M-F 9am to 5pm<br>';
												echo 'Lunch 12 -1<br>';
												echo 'Sat 9 -12<br>';
												echo 'Closed Sun & Mon<br><br>';
												echo 'We are Excited to Now be Offering Tires for your Car, Truck, SUV, Trailers and More!<br>';
												echo '<b><a class="no-decoration" href="http://www.howellscycle.com">Visit Us Online</a></b><br>';
											echo '</p>';
										echo '</div>';
									echo '</div>';
								echo '</li>';
								echo '<li>';
									echo '<div class="latest-model">';
										echo '<div class="latest-model__img">';
											echo '<img alt="bike" class="img-responsive" src="'.$this->Style->MEDIA_DIR().'270x270/toys4bigboys_270x270.png" />';
										echo '</div>';
										echo '<div class="latest-model__info">';
											echo '<h5>Toys For Big Boys</h5>';
											echo '<p class="blog-text">';
												echo '<b>Address</b><br>';
												echo '2701 NW 2nd Ave Suite 213<br>';
												echo 'Boca Raton, FL 33431<br><br>';
												echo '<b>Phone</b><br>';
												echo 'Phone: 1-855-553-TOYS(8697)<br><br>';
												echo '<b>URL</b><br>';
												echo '<b><a class="no-decoration" href="http://www.toysforboys.com">Visit Us!</a></b><br><br>';
												echo '<b>Contact</b><br>';
												echo '<b><a href="mailto:Contact@toysforbigboys.com" target="_top">Send Us An Message</a></b>';
											echo '</p>';
										echo '</div>';
									echo '</div>';
								echo '</li>';
								echo '<li>';
									echo '<div class="latest-model">';
										echo '<div class="latest-model__img">';
											echo '<a href="http://wheelsontheroad.com"><img alt="bike" class="img-responsive" src="'.$this->Style->MEDIA_DIR().'270x270/mike.png" /></a>';
										echo '</div>';
									echo '</div>';
								echo '</li>';
							echo '</ul>';

						echo '</div>';
					echo '</aside>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</div>'; # blog-page
?>