<?php
	Design::get_other_header();
	Design::get_other_navigation();
	echo '<section class="status status--dark dark-bg--about"></section>'; # status

	echo '<section class="about-us">';
		echo '<div class="container">';
			echo '<div class="row">';
				echo '<div class="col-sm-10 col-sm-offset-1 col-xs-12">';
					echo '<h1 class=" wow slideInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">We are a team of <span>passoniate people</span> who love to make, enjoy and drive motorcycles!</h1>';
					echo '<div class="about-us__mission wow slideInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
						echo '<div><span class="fa  fa-quote-right"></span></div>';
						echo '<h2>Our Mission<span class="line line--title line--center"><span class="line__first"></span><span class="line__second"></span></span></h2>';
					echo '</div>';
					echo '<p class="about-us__text wow slideInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">Proin blandit quam molestie luctus vehicula orci massa interdum justo nec rutrum risus augue ut nisl  ultric lacu at  Etiam eleifend nisl nec lectus. Maecenas sit amet mi. Donec erat. Fusce quis nisl ac sapien tristique dapibus. Donec rhoncus nulla sem nisi fermentum quis.</p>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</section>'; # about-us
	echo '<section class="anons anons--about">';
		echo '<div class="container">';
			echo '<div class="after anons__main">';
				echo '<div class="row">';
					echo '<div class="col-md-4 col-xs-12 wow slideInLeft" data-wow-delay="0.7s" data-wow-duration="2.5s">';
						echo '<div class="anons__block anons__block--center triangle--block line-down triangle">';
							echo '<div class="anons__photo"><img class="img-responsive" src="media/370x200/about1.jpg" alt="news"/></div>';
							echo '<div class="anons__title">';
								echo '<h2><a href="article.html" class="title no-decoration"><span class="title__bold">Who</span>WeAre</a></h2>';
							echo '</div>';
							echo '<div class="anons__text">';
								echo '<p class="text">Nunc molestie sapien tempor placerat Cras et lectus Etiam sit amet turpis. Suspendisse erad Proin ans ipsum vitae orci porta.</p>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
					echo '<div class="col-md-4 col-xs-12 wow slideInLeft" data-wow-delay="0.7s" data-wow-duration="1.5s">';
						echo '<div class="anons__block anons__block--center triangle--block line-down triangle">';
							echo '<div class="anons__photo"><img class="img-responsive" src="'.$cfg["FTW_IMAGES"].'media/370x200/about3.jpg" alt="news"/></div>';
							echo '<div class="anons__title">';
								echo '<h2><a href="?id=article" class="title no-decoration"><span class="title__bold">Full Throttle</span>History</a></h2>';
							echo '</div>';
							echo '<div class="anons__text">';
								echo '<p class="text">Nunc molestie sapien tempor placerat Cras et lectus Etiam sit amet turpis. Suspendisse erad Proin ans ipsum vitae orci porta.</p>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
					echo '<div class="col-md-4 col-xs-12 wow slideInLeft" data-wow-delay="0.7s">';
						echo '<div class="anons__block anons__block--center triangle--block line-down triangle">';
							echo '<div class="anons__photo"><img class="img-responsive" src="'.$cfg["FTW_IMAGES"].'media/370x200/about2.jpg" alt="news"/></div>';
							echo '<div class="anons__title">';
								echo '<h2><a href="?id=article" class="title no-decoration"><span class="title__bold">Why</span>JoinUs</a></h2>';
							echo '</div>';
							echo '<div class="anons__text">';
								echo '<p class="text">Nunc molestie sapien tempor placerat Cras et lectus Etiam sit amet turpis. Suspendisse erad Proin ans ipsum vitae orci porta.</p>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</section>'; # anons
	echo '<section class="about-info">';
		echo '<div class="container">';
			echo '<div class="row">';
				echo '<div class="col-md-5 col-xs-12 wow slideInLeft" data-wow-delay="0.7s" data-wow-duration="1.5s">';
					echo '<div class="services__info">';
						echo '<div class="services__info-block">';
							echo '<h5 class="clearfix services__title"><a class="pull-left no-decoration js-toggle" href="#">Motorcycle Inspection</a><a class="square square--toggle pull-right js-toggle"><span class="fa fa-plus"></span></a></h5>';
							echo '<div class="services__text triangle triangle--services">';
								echo 'Nunc molestie sapien tempor placerat Cras et lectus. Etiam sit amet turpis. Suspendisse et erat. Ut  Proin a ipsum vitae orci porta tristique nam. Class aptent taciti sociosqu ad sodales';
							echo '</div>';
						echo '</div>';
						echo '<div class="services__info-block">';
							echo '<h5 class="clearfix services__title"><a class="pull-left no-decoration js-toggle" href="#">Finance And Insurance</a><a class="square square--toggle pull-right js-toggle"><span class="fa fa-plus"></span></a></h5>';
							echo '<div class="services__text triangle triangle--services">';
								echo 'Nunc molestie sapien tempor placerat Cras et lectus. Etiam sit amet turpis. Suspendisse et erat. Ut  Proin a ipsum vitae orci porta tristique nam. Class aptent taciti sociosqu ad sodales';
							echo '</div>';
						echo '</div>';
						echo '<div class="services__info-block">';
							echo '<h5 class="clearfix services__title"><a class="pull-left no-decoration js-toggle" href="#">Ready For the Racing</a><a class="square square--toggle pull-right js-toggle"><span class="fa fa-plus"></span></a></h5>';
							echo '<div class="services__text triangle triangle--services">';
								echo 'Nunc molestie sapien tempor placerat Cras et lectus. Etiam sit amet turpis. Suspendisse et erat. Ut  Proin a ipsum vitae orci porta tristique nam. Class aptent taciti sociosqu ad sodales';
							echo '</div>';
						echo '</div>';
						echo '<div class="services__info-block">';
							echo '<h5 class="clearfix services__title"><a class="pull-left no-decoration js-toggle" href="#">Tyre And Oil Change</a><a class="square square--toggle pull-right js-toggle"><span class="fa fa-plus"></span></a></h5>';
							echo '<div class="services__text triangle triangle--services">';
								echo 'Nunc molestie sapien tempor placerat Cras et lectus. Etiam sit amet turpis. Suspendisse et erat. Ut  Proin a ipsum vitae orci porta tristique nam. Class aptent taciti sociosqu ad sodales';
							echo '</div>';
						echo '</div>';
						echo '<div class="services__info-block">';
							echo '<h5 class="clearfix services__title"><a class="pull-left no-decoration js-toggle" href="#">Parts Replacement</a><a class="square square--toggle pull-right js-toggle"><span class="fa fa-plus"></span></a></h5>';
							echo '<div class="services__text triangle triangle--services">';
								echo 'Nunc molestie sapien tempor placerat Cras et lectus. Etiam sit amet turpis. Suspendisse et erat. Ut  Proin a ipsum vitae orci porta tristique nam. Class aptent taciti sociosqu ad sodales';
							echo '</div>';
						echo '</div>';
						echo '<div class="services__info-block">';
							echo '<h5 class="clearfix services__title"><a class="pull-left no-decoration js-toggle" href="#"> Accident Repairs And Quotes</a><a class="square square--toggle pull-right js-toggle"><span class="fa fa-plus"></span></a></h5>';
							echo '<div class="services__text triangle triangle--services">';
								echo 'Nunc molestie sapien tempor placerat Cras et lectus. Etiam sit amet turpis. Suspendisse et erat. Ut  Proin a ipsum vitae orci porta tristique nam. Class aptent taciti sociosqu ad sodales';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
				echo '<div class="col-md-7 col-xs-12 wow slideInRight" data-wow-delay="0.7s" data-wow-duration="1.5s">';
					echo '<div class="aside-tabs aside-tabs--about">';
						echo '<div class="aside-tabs__links">';
							echo '<a href="#" class="no-decoration aside-tabs__active-link js-tab-link" data-for="#info1">BIKE TRENDS</a>';
							echo '<a href="#" class="no-decoration js-tab-link" data-for="#info2">MEMBERS RIDES</a>';
							echo '<a href="#" class="no-decoration js-tab-link" data-for="#info3">recent updates</a>';
						echo '</div>';
						echo '<div class="aside-tabs__blocks about-tab js-tab-block" id="info1">';
							echo '<div class="about-tab__img">';
								echo '<img src="media/570x180/about-tab.jpg" alt="bike" class="img-responsive" />';
							echo '</div>';
							echo '<p>Nunc molestie sapien tempor placerat cras et lectus. Etiam sit amet turpis disce et erat. Prona ipsum vitae orci pords tristiqu nam. Lorem ipsum dolor amet consectetur adipisicing el sed do eiusmod tempor incididunt dut labore et dolore magna aliqua enimad minim veniam quis nos rud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>';
							echo '<div class="row">';
								echo '<div class="col-xs-6">';
									echo '<ul class="triangle-list">';
										echo '<li class="triangle triangle-list__one">Nullam ac velit fusce consequat</li>';
										echo '<li class="triangle triangle-list__one">Sed elit non ipsum</li>';
									echo '</ul>';
								echo '</div>';
								echo '<div class="col-xs-6">';
									echo '<ul class="triangle-list">';
										echo '<li class="triangle triangle-list__one">Nam ullamcorper ipsum quis erat</li>';
										echo '<li class="triangle triangle-list__one">Duis convallis ruturm mauris</li>';
									echo '</ul>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
						echo '<div class="aside-tabs__blocks about-tab js-tab-block" id="info2">';
							echo '<div class="about-tab__img">';
								echo '<img src="media/570x180/about-tab-2.jpg" alt="bike" class="img-responsive" />';
							echo '</div>';
							echo '<p>Nunc molestie sapien tempor placerat cras et lectus. Etiam sit amet turpis disce et erat. Prona ipsum vitae orci pords tristiqu nam. Lorem ipsum dolor amet consectetur adipisicing el sed do eiusmod tempor incididunt dut labore et dolore magna aliqua enimad minim veniam quis nos rud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>';
						echo '</div>';
						echo '<div class="aside-tabs__blocks about-tab js-tab-block" id="info3">';
							echo '<div class="about-tab__img">';
								echo '<img src="media/570x180/about-tab-3.jpg" alt="bike" class="img-responsive" />';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</section>'; # about-info
	echo '<section class="team">';
		echo '<div class="container">';
			echo '<h2 class="title title--main wow slideInRight" data-wow-delay="0.7s" data-wow-duration="1.5s"><span class="title__bold">Full Throttle</span>Warranty Team<span class="line line--title"><span class="line__first"></span><span class="line__second"></span></span></h2>';
			echo '<p class="text text--anons wow slideInRight" data-wow-delay="0.7s" data-wow-duration="1.5s">Nullam ac velit. Fusce consequat ipsum non ipsum. Nam ullamcorper ipsum quis erat. Aliquam non elit. In vitae dui sagittis cursus. Duis convallis rutrum mauris. Maecenas eu neque lacinia.</p>';
			echo '<div class="js-personal-slider enable-owl-carousel" data-auto-play="5000" data-stop-on-hover="true" data-items="2" data-pagination="false" data-navigation="true" data-items-desktop="3" data-items-desktop-small="3" data-items-tablet="2" data-items-tablet-small="2">';
				echo '<div class="slider-item wow zoomInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
					echo '<div class="worker triangle line-down triangle--big">';
						echo '<div class="worker__photo">';
							echo '<img src="'.$cfg["FTW_IMAGES"].'media/persons/worker1.jpg" alt="person" class="img-responsive" />';
						echo '</div>';
						echo '<div class="worker__info">';
							echo '<h2>David Miller</h2>';
							echo '<p class="text">Club Founder</p>';
							echo '<p class="text">Phone: +1 264 9852</p>';
						echo '</div>';
						echo '<div class="woker-hidden">';
							echo '<div class="woker-hidden__social">';
								echo '<div class="social social--footer social--footer-home clearfix">';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-twitter"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-facebook"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-google-plus"></span>';
									echo '</a>';
								echo '</div>';
								echo '<div class="worker__info">';
									echo '<h2>David Miller</h2>';
									echo '<p class="text">Club Founder</p>';
									echo '<p class="text">Phone: +1 264 9852</p>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
				echo '<div class="slider-item wow zoomInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
					echo '<div class="worker triangle line-down triangle--big">';
						echo '<div class="worker__photo">';
							echo '<img src="'.$cfg["FTW_IMAGES"].'media/persons/worker2.jpg" alt="person" class="img-responsive" />';
						echo '</div>';
						echo '<div class="worker__info">';
							echo '<h2>Martina Webber</h2>';
							echo '<p class="text">Expert Racer</p>';
							echo '<p class="text">Phone: +1 264 9852</p>';
						echo '</div>';
						echo '<div class="woker-hidden">';
							echo '<div class="woker-hidden__social">';
								echo '<div class="social social--footer social--footer-home clearfix">';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-twitter"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-facebook"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-google-plus"></span>';
									echo '</a>';
								echo '</div>';
								echo '<div class="worker__info">';
									echo '<h2>Martina Webber</h2>';
									echo '<p class="text">Expert Racer</p>';
									echo '<p class="text">Phone: +1 264 9852</p>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
				echo '<div class="slider-item wow zoomInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
					echo '<div class="worker triangle line-down triangle--big">';
						echo '<div class="worker__photo">';
							echo '<img src="'.$cfg["FTW_IMAGES"].'media/persons/worker3.jpg" alt="person" class="img-responsive" />';
						echo '</div>';
						echo '<div class="worker__info">';
							echo '<h2>Jeff Robinson</h2>';
							echo '<p class="text">Management</p>';
							echo '<p class="text">Phone: +1 264 9852</p>';
						echo '</div>';
						echo '<div class="woker-hidden">';
							echo '<div class="woker-hidden__social">';
								echo '<div class="social social--footer social--footer-home clearfix">';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-twitter"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-facebook"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-google-plus"></span>';
									echo '</a>';
								echo '</div>';
								echo '<div class="worker__info">';
									echo '<h2>Jeff Robinson</h2>';
									echo '<p class="text">Management</p>';
									echo '<p class="text">Phone: +1 264 9852</p>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
				echo '<div class="slider-item wow zoomInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
					echo '<div class="worker triangle line-down triangle--big">';
						echo '<div class="worker__photo">';
							echo '<img src="'.$cfg["FTW_IMAGES"].'media/persons/worker4.jpg" alt="person" class="img-responsive" />';
						echo '</div>';
						echo '<div class="worker__info">';
							echo '<h2>Andrea Deo</h2>';
							echo '<p class="text">Events Organizer</p>';
							echo '<p class="text">Phone: +1 264 9852</p>';
						echo '</div>';
						echo '<div class="woker-hidden">';
							echo '<div class="woker-hidden__social">';
								echo '<div class="social social--footer social--footer-home clearfix">';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-twitter"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-facebook"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-google-plus"></span>';
									echo '</a>';
								echo '</div>';
									echo '<div class="worker__info">';
									echo '<h2>Andrea Deo</h2>';
									echo '<p class="text">Events Organizer</p>';
									echo '<p class="text">Phone: +1 264 9852</p>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
				echo '<div class="slider-item wow zoomInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
					echo '<div class="worker triangle line-down triangle--big">';
						echo '<div class="worker__photo">';
							echo '<img src="'.$cfg["FTW_IMAGES"].'media/persons/worker4.jpg" alt="person" class="img-responsive" />';
						echo '</div>';
						echo '<div class="worker__info">';
							echo '<h2>Andrea Deo</h2>';
							echo '<p class="text">Events Organizer</p>';
							echo '<p class="text">Phone: +1 264 9852</p>';
						echo '</div>';
						echo '<div class="woker-hidden">';
							echo '<div class="woker-hidden__social">';
								echo '<div class="social social--footer social--footer-home clearfix">';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-twitter"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-facebook"></span>';
									echo '</a>';
									echo '<a href="#" class="social__one square">';
										echo '<span class="fa fa-google-plus"></span>';
									echo '</a>';
								echo '</div>';
								echo '<div class="worker__info">';
									echo '<h2>Andrea Deo</h2>';
									echo '<p class="text">Events Organizer</p>';
									echo '<p class="text">Phone: +1 264 9852</p>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</section>';
?>