<?php
	echo '<header id="header-top" class="top-header">';
		echo '<div class="container">';
			echo '<div class="top-header__main wow slideInDown" data-wow-delay="0.7s" data-wow-duration="1.5s">';
				echo '<div class="row">';
					echo '<div class="col-xs-4">';
						echo '<div class="social social--top clearfix">';
							echo '<a href="#" class="social__one square">';
								echo '<span class="fa fa-twitter"></span>';
							echo '</a>';
							echo '<a href="#" class="social__one square">';
								echo '<span class="fa fa-facebook"></span>';
							echo '</a>';
							echo '<a href="#" class="social__one square">';
								echo '<span class="fa fa-google-plus"></span>';
							echo '</a>';
							echo '<a href="#" class="social__one square">';
								echo '<span class="fa fa-pinterest"></span>';
							echo '</a>';
							echo '<a href="#" class="social__one square">';
								echo '<span class="fa fa-instagram"></span>';
							echo '</a>';
						echo '</div>';
					echo '</div>';
					echo '<div class="col-xs-8">';
						echo '<div class="header-contacts clearfix">';
							echo '<div class="header-contacts__one">';
								echo '<a href="contacts.html" class="header-contacts__phone square">';
									echo '<span class="fa fa-phone"></span>';
								echo '</a>';
								echo '<a href="contacts.html" class="header-contacts__link">0800 123 4567</a>';
							echo '</div>';
							echo '<div class="header-contacts__one">';
								echo '<a href="contacts.html" class="header-contacts__email square">';
									echo '<span class="fa fa-envelope"></span>';
								echo '</a>';
								echo '<a href="contacts.html" class="header-contacts__link">info@domain.com</a>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</header>';
	echo '<nav class="top-nav">';
		echo '<div class="container">';
			echo '<div class="top-nav__main">';
				echo '<div class="row">';
					echo '<div class="col-md-3 col-xs-12">';
						echo '<a href="home-main.html" class="logo">';
							echo '<span class="logo__moto">';
								echo '<img src="'.$cfg["FTW_IMAGES"].'svg/logo.svg" alt="logo">';
							echo '</span>';
							echo '<h2 class="logo__title">';
								echo 'BIKER<span>Club</span>';
							echo '</h2>';
						echo '</a>';
					echo '</div>';
					echo '<div class="col-md-9 col-xs-12">';
						echo '<div class="main-nav navbar-main-slide">';
							echo '<a href="#" class="btn_header_search main-nav__search no-decoration">';
								echo '<span class="fa fa-search"></span>';
							echo '</a>';
							echo '<div class="navbar-header">';
								echo '<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav">';
									echo '<span class="sr-only">Toggle navigation</span>';
									echo '<span class="icon-bar"></span>';
									echo '<span class="icon-bar"></span>';
									echo '<span class="icon-bar"></span>';
								echo '</button>';
							echo '</div>';
							echo '<ul class="collapse navbar-collapse navbar-nav-menu" id="nav">';
								echo '<li><a class="no-decoration" href="?id=home">Home</a><span class="main-nav__separator"><span></span><span></span><span></span></span></li>';
								echo '<li><a class="no-decoration" href="?id=about">About us</a><span class="main-nav__separator"><span></span><span></span><span></span></span></li>';
								echo '<li><a class="no-decoration" href="?id=shop">Offer</a><span class="main-nav__separator"><span></span><span></span><span></span></span></li>';
								echo '<li><a class="no-decoration" href="?id=article">Services</a><span class="main-nav__separator"><span></span><span></span><span></span></span></li>';
								echo '<li><a class="no-decoration" href="?id=item">Listings</a><span class="main-nav__separator"><span></span><span></span><span></span></span></li>';
								echo '<li><a class="no-decoration" href="?id=blog">Blog</a><span class="main-nav__separator"><span></span><span></span><span></span></span></li>';
								echo '<li><a class="no-decoration" href="?id=contacts">Contact</a><span class="main-nav__separator"><span></span><span></span><span></span></span></li>';
								echo '<li><a class="no-decoration" href="?id=shop">Shop</a></li>';
							echo '</ul>';
							echo '<div class="search-form-modal transition">';
								echo '<form class="navbar-form header_search_form">';
									echo '<i class="fa fa-times search-form_close"></i>';
									echo '<div class="form-group">';
										echo '<input type="text" class="form-control" placeholder="Search">';
									echo '</div>';
									echo '<button type="submit" class="btn btn_search customBgColor">Search</button>';
								echo '</form>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</nav>';

	echo '<section class="status status--shop dark-bg dark-bg--shop">';
		echo '<div class="container wow slideInRight" data-wow-delay="0.7s" data-wow-duration="1.5s">';
			echo '<div class="breadcumb">';
				echo '<a href="home.html" class="breadcumb__page no-decoration">Home</a>';
				echo '<span class="breadcumb__del no-decoration">&raquo;</span>';
				echo '<a href="shop.html" class="breadcumb__page no-decoration">Store</a>';
			echo '</div>';
			echo '<h2 class="title title--page"><span class="title__bold">Products</span> Shop</h2>';
		echo '</div>';
	echo '</section>';

	echo '<section class="shop">';
		echo '<div class="container">';
			echo '<div class="row">';
				echo '<div class="col-sm-10 col-sm-offset-1 col-xs-12">';
					echo '<div class="about-us about-us--shop wow zoomInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
						echo '<h1>Our online store offers wide range of <span>Bikes and Motorcycles</span> products at cheap rates!</h1>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
			echo '<div class="row row--main-shop">';
				echo '<div class="col-lg-3 col-md-4 col-sm-5 col-xs-6">';
					echo '<aside class="shop-aside">';
						echo '<form class=" wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s" action="/" method="post">';
							echo '<div class="relative-pos shop-aside__search">';
								echo '<input type="text" name="search" placeholder="Search..." />';
								echo '<button type="submit"><span class="fa fa-search"></span></button>';
							echo '</div>';
						echo '</form>';
						echo '<div class="shop-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h2 class="shop-title">SHOP Categories<span class="line line--title line--shop"><span class="line__first"></span><span class="line__second"></span></span></h2>';
							echo '<ul class="triangle-list triangle-list--shop">';
								echo '<li class="triangle triangle-list__one"><a class="no-decoration" href="#">Body Parts</a></li>';
								echo '<li class="triangle triangle-list__one"><a class="no-decoration" href="#">Brakes</a></li>';
								echo '<li class="triangle triangle-list__one triangle-list__one--active"><a class="no-decoration" href="#">Dash and Gauges</a></li>';
								echo '<li class="triangle triangle-list__one"><a class="no-decoration" href="#">Engine Parts /Accessories</a></li>';
								echo '<li class="triangle triangle-list__one"><a class="no-decoration" href="#">Fuel and Air</a></li>';
								echo '<li class="triangle triangle-list__one"><a class="no-decoration" href="#">Tire and Wheels</a></li>';
							echo '</ul>';
						echo '</div>';
						echo '<div class="shop-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h2 class="shop-title">Filter by price<span class="line line--title line--shop"><span class="line__first"></span><span class="line__second"></span></span></h2>';
							echo '<div class="js-shop-slider price-slider"></div>';
							echo '<div class="clearfix">';
								echo '<form action="/" method="post" class="price-num">';
									echo 'Price:';
									echo '$<span class="js-min">100</span> - $<span class="js-max">1000</span>';
									echo '<input type="hidden" name="min" class="js-min-input" />';
									echo '<input type="hidden" name="min" class="js-max-input" />';
								echo '</form>';
								echo '<button class="button button--main button--filter button--dark btn pull-right">FILTER</button>';
							echo '</div>';
						echo '</div>';
						echo '<div class="shop-aside__block wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h2 class="shop-title">FEATURED PRODUCTS<span class="line line--title line--shop"><span class="line__first"></span><span class="line__second"></span></span></h2>';
							echo '<div class="shop-aside__featured">';
								echo '<div class="shop-aside__product clearfix">';
									echo '<div class="pull-right">';
										echo '<img src="media/featured-products/product1.jpg" alt="product"/>';
									echo '</div>';
									echo '<div class="shop-aside__desc">';
										echo '<h4><a class="no-decoration" href="item.html">C3 Pro Helmet</a></h4>';
										echo '<div class="item-price">$799.00</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="shop-aside__product clearfix">';
									echo '<div class="pull-right">';
										echo '<img src="media/featured-products/product2.jpg" alt="product"/>';
									echo '</div>';
									echo '<div class="shop-aside__desc">';
										echo '<h4><a class="no-decoration" href="item.html">Scorpion SGS Gloves</a></h4>';
										echo '<div class="item-price">$79.95</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="shop-aside__product clearfix">';
									echo '<div class="pull-right">';
										echo '<img src="media/featured-products/product3.jpg" alt="product"/>';
									echo '</div>';
									echo '<div class="shop-aside__desc">';
										echo '<h4><a class="no-decoration" href="item.html">Sports Leather Jacket</a></h4>';
										echo '<div class="item-price">$439.95</div>';
									echo '</div>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
					echo '</aside>';
				echo '</div>';
				echo '<div class="col-lg-9 col-md-8 col-sm-7 col-xs-6">';
					echo '<div class="shop-main">';
						echo '<header class="shop-main__head clearfix wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
							echo '<h4 class="pull-left">Showing 1-9 of 46 results</h4>';
							echo '<a href="#" class="button button--grey button--main btn button--active pull-right">Sort by</a>';
						echo '</header>';
						echo '<div class="items">';
							echo '<div class="row">';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product1.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">Plug Cigarette Lighter Adapter</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="sale triangle-sale"><span>Sale</span></div>';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product2.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">Diamond Base With Ball</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price item-price--old pull-left">$79.95</div>';
												echo '<div class="item-price pull-left">$54.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInRight" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product3.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">Schuberth C3 Pro Helmet</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product4.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">RAM Mounts Aqua Box</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product5.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">Knob With Keyed Lock</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInRight" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product6.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">Nolan N-COM Battery</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product7.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">Force Helmet Communicator</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInUp" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product8.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">GT-R Air Textile Jacket</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
								echo '<div class="col-lg-4 col-sm-6 col-xs-12 wow fadeInRight" data-wow-delay="0.7s" data-wow-duration="1.5s">';
									echo '<div class="item-cell js-cell equal-height-item">';
										echo '<div class="item-cell__top">';
											echo '<div class="sale triangle-sale"><span>Sale</span></div>';
											echo '<div class="item-cell__img">';
												echo '<img src="media/products/product9.jpg" class="img-responsive center-block" alt="item"/>';
											echo '</div>';
											echo '<div class="item-cell__actions">';
												echo '<a href="#" class="add-to-cart"><span class="fa fa-shopping-cart"></span></a>';
												echo '<a href="#" class="see-detail"><span class="fa fa-search-plus"></span></a>';
											echo '</div>';
										echo '</div>';
										echo '<div class="item-cell__bottom">';
											echo '<h1 class="item-title"><a class="no-decoration" href="item.html">Cradle Holster Spot Is</a></h1>';
											echo '<div class="item-cell__info clearfix">';
												echo '<div class="item-price item-price--old pull-left">$99.95</div>';
												echo '<div class="item-price pull-left">$79.95</div>';
												echo '<div class="stars pull-right">';
													echo '<span class="star star--none"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
													echo '<span class="star"></span>';
												echo '</div>';
											echo '</div>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
							echo '</div>';
							echo '<div class="pagination wow fadeInRight" data-wow-delay="0.7s" data-wow-duration="1.5s">';
								echo '<span class="pagination__text">Page 1 of 6</span>';
								echo '<span class="pagination__row">';
									echo '<a href="#" class="pagination__cell pagination__cell--nav no-decoration">&laquo;</a>';
									echo '<a href="#" class="pagination__cell no-decoration">1</a>';
									echo '<a href="#" class="pagination__cell pagination__cell--active no-decoration">2</a>';
									echo '<a href="#" class="pagination__cell no-decoration">3</a>';
									echo '<a href="" class="pagination__cell pagination__cell--nav no-decoration">&raquo;</a>';
								echo '</span>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</section>';
?>