USE [master]<br>
GO
<br><br>
CREATE DATABASE [PS_ChatLog]<br>
 CONTAINMENT = NONE<br>
 ON  PRIMARY <br>
( NAME = N'PS_ChatLog_Data', FILENAME = N'C:\ShaiyaServer\DevData\PS_ChatLog.mdf' , SIZE = 2560KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)<br>
 LOG ON <br>
( NAME = N'PS_ChatLog_Log', FILENAME = N'C:\ShaiyaServer\DevData\PS_ChatLog.ldf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET COMPATIBILITY_LEVEL = 90<br>
GO
<br><br>
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))<br>
begin<br>
EXEC [PS_ChatLog].[dbo].[sp_fulltext_database] @action = 'disable'<br>
end<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET ANSI_NULL_DEFAULT OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET ANSI_NULLS OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET ANSI_PADDING OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET ANSI_WARNINGS OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET ARITHABORT OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET AUTO_CLOSE ON<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET AUTO_CREATE_STATISTICS ON<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET AUTO_SHRINK ON<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET AUTO_UPDATE_STATISTICS ON<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET CURSOR_DEFAULT  GLOBAL<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET CONCAT_NULL_YIELDS_NULL OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET NUMERIC_ROUNDABORT OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET QUOTED_IDENTIFIER OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET RECURSIVE_TRIGGERS OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET  DISABLE_BROKER<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET DATE_CORRELATION_OPTIMIZATION OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET TRUSTWORTHY OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET ALLOW_SNAPSHOT_ISOLATION OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET PARAMETERIZATION SIMPLE<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET READ_COMMITTED_SNAPSHOT OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET HONOR_BROKER_PRIORITY OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET RECOVERY SIMPLE<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET  MULTI_USER<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET PAGE_VERIFY TORN_PAGE_DETECTION<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET DB_CHAINING OFF<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET TARGET_RECOVERY_TIME = 0 SECONDS<br>
GO
<br><br>
ALTER DATABASE [PS_ChatLog] SET  READ_WRITE<br>
GO
<br><br>

